parameters:
  netzmacht.contao_form_designer.defaults:
    templates:
      layout: 'fd_layout_row'
      error:  'fd_error_latest'
      control: 'fd_control_default'
      label:  'fd_label_default'
      help:   'fd_help_default'
    
  netzmacht.contao_form_designer.widgets:
    captcha:
      templates:
        control: 'fd_control_captcha'
    checkbox:
      templates:
        control: 'fd_control_checkbox'
        layout:  'fd_layout_row_field'
    explanation:
      templates:
        control: 'fd_control_explanation'
        layout:  'fd_layout_row_field'
    message:
      templates:
        control: 'fd_control_message'
    password:
      templates:
        control: 'fd_control_password'
        layout:  'fd_layout_row_password'
    radio:
      templates:
        control: 'fd_control_radio'
        layout:  'fd_layout_row_field'
    select:
      templates:
        control: 'fd_control_select'
    submit:
      templates:
        control: 'fd_control_submit'
        layout:  'fd_layout_row_field'
    textarea:
      templates:
        control: 'fd_control_textarea'
    text:
      templates:
        control: 'fd_control_text'
    url:
      templates:
        control: 'fd_control_text'
    email:
      templates:
        control: 'fd_control_text'
    number:
      templates:
        control: 'fd_control_text'
    upload:
      templates:
        control: 'fd_control_upload'

  netzmacht.contao_form_designer.form_designer.modules:
    - 'comments'
    - 'form'

  netzmacht.contao_form_designer.form_designer.elements:
    - 'comments'
    - 'form'
