services:
  netzmacht.contao_form_designer.listener.contextual_form_layout:
    class: Netzmacht\Contao\FormDesigner\Listener\ContextualFormLayoutListener
    arguments:
      - '@netzmacht.contao_form_designer.layout_manager'
      - '@netzmacht.contao_form_designer.repository.layout'
      - '@netzmacht.contao_form_designer.layout_factory'
      - '@monolog.logger.contao'

  netzmacht.contao_form_designer.listener.theme_form_layout:
    class: Netzmacht\Contao\FormDesigner\Listener\ThemeFormLayoutListener
